version: '3.8'

services:
  node_backend:
    container_name: phantom-dominators
    image: phantom-dominators:0.0.1
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - EXTERNAL_PORT=5000
      - PGDATABASE=phantomdb
      - PGUSER=hekwizera
      - PGPASSWORD=12345
      - PGHOST=node_db
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hekwizera
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=phantomdb
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}
